'use strict';

const API_RATELIMIT_LIMIT = 300;

const API_COMMAND_TYPE_COMMAND = 'command';
const API_COMMAND_TYPE_COMMAND_WAKES = 'command_wakes';

const API_REQUEST_COUNTER_READ = 'api_read';
const API_REQUEST_COUNTER_COMMAND = 'api_command';
const API_REQUEST_COUNTER_COMMAND_WAKES = 'api_command_wakes';

const API_ERROR_READ = 'api_error_read';
const API_ERROR_COMMAND = 'api_error_command';

const COMMAND_API_REST = 'rest';
const COMMAND_API_PROXY = 'command';
const COMMAND_API_CMD = 'tvcp';

const DOMAIN_INFOTAINMENT = 'DOMAIN_INFOTAINMENT';
const DOMAIN_VEHICLE_SECURITY = 'DOMAIN_VEHICLE_SECURITY';

const STATE_ONLINE = 'online';
const STATE_OFFLINE = 'offline';
const STATE_ASLEEP = 'asleep';
const STATE_RATE_LIMIT = 'ratelimit';

const CHARGING_STATE_DISCONNECTED = 'Disconnected';
const CHARGING_STATE_CALIBRATING = 'Calibrating';
const CHARGING_STATE_COMPLETE = 'Complete';
const CHARGING_STATE_NOPOWER = 'NoPower';
const CHARGING_STATE_STOPPED = 'Stopped';
const CHARGING_STATE_UNKNOWN = 'Unknown';
const CHARGING_STATE_STARTING = 'Starting';
const CHARGING_STATE_CHARGING = 'Charging';

const SOFTWARE_UPDATE_STATE_AVAILABLE = 'available';
const SOFTWARE_UPDATE_STATE_SCHEDULEDE = 'scheduled';
const SOFTWARE_UPDATE_STATE_INSTALLING = 'installing';
const SOFTWARE_UPDATE_STATE_DOWNLOADING = 'downloading';
const SOFTWARE_UPDATE_STATE_DOWNLOADING_WIFI_WAIT = 'downloading_wifi_wait';

const MEDIA_PLAYBACK_STATE_PLAYING = 'Playing';
const MEDIA_PLAYBACK_STATE_STOPPED = 'Stopped';

const WINDOW_POSITION_VENT = 'vent';
const WINDOW_POSITION_CLOSE = 'close';
const TRUNK_FRONT = 'front';
const TRUNK_REAR = 'rear';

const MILES_TO_KM = 1.609344;

const API_ERRORS_WHITELIST = [
    'already_set',
    'not_charging',
    'is_charging',
    'requested'
];

module.exports = Object.freeze({
    API_RATELIMIT_LIMIT,
    API_COMMAND_TYPE_COMMAND,
    API_COMMAND_TYPE_COMMAND_WAKES,
    API_REQUEST_COUNTER_READ,
    API_REQUEST_COUNTER_COMMAND,
    API_REQUEST_COUNTER_COMMAND_WAKES,
    API_ERROR_READ,
    API_ERROR_COMMAND,
    STATE_ONLINE,
    STATE_OFFLINE,
    STATE_ASLEEP,
    STATE_RATE_LIMIT,
    MILES_TO_KM,
    WINDOW_POSITION_VENT,
    WINDOW_POSITION_CLOSE,
    COMMAND_API_REST,
    COMMAND_API_PROXY,
    COMMAND_API_CMD,
    DOMAIN_INFOTAINMENT,
    DOMAIN_VEHICLE_SECURITY,
    TRUNK_FRONT,
    TRUNK_REAR,
    CHARGING_STATE_DISCONNECTED,
    CHARGING_STATE_CALIBRATING,
    CHARGING_STATE_COMPLETE,
    CHARGING_STATE_NOPOWER,
    CHARGING_STATE_STOPPED,
    CHARGING_STATE_UNKNOWN,
    CHARGING_STATE_STARTING,
    CHARGING_STATE_CHARGING,
    SOFTWARE_UPDATE_STATE_AVAILABLE,
    SOFTWARE_UPDATE_STATE_SCHEDULEDE,
    SOFTWARE_UPDATE_STATE_INSTALLING,
    SOFTWARE_UPDATE_STATE_DOWNLOADING,
    SOFTWARE_UPDATE_STATE_DOWNLOADING_WIFI_WAIT,
    MEDIA_PLAYBACK_STATE_PLAYING,
    MEDIA_PLAYBACK_STATE_STOPPED,
    API_ERRORS_WHITELIST
})